sudo: false
addons:
    apt:
        sources:
            - deadsnakes
        packages:
            - python3.5
            - python3.5-dev
            - python-pip
            - python-virtualenv

language: cpp
compiler:
    - gcc
    - clang

before_install:
    - python3.5 -m venv env --without-pip
    - source env/bin/activate
    - python --version
    - wget https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py
    - pip install cvra-packager~=1.0.0
    - pip install msgpack-python==0.4.8 PyYAML==3.11

    - pushd ..
    - wget "https://github.com/cpputest/cpputest.github.io/blob/master/releases/cpputest-3.6.tar.gz?raw=true" -O cpputest.tar.gz
    - tar -xzf cpputest.tar.gz
    - cd cpputest-3.6/
    - ./configure
    - make
    - sudo make install
    - popd

before_script:
    - packager
    - mkdir build/
    - cd build/
    - cmake ..

script:
    - make
    - ./tests
